<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="peregrineit-ThinkPad-L14-Gen-3" failures="1" tests="2" name="Surefire test" time="58.493" errors="0" timestamp="2025-07-02T17:51:23 IST">
  <testcase classname="attendanceTests.AccessControlTests" name="testAccessGrantedRecordsRetrieval" time="58.426">
    <failure type="java.lang.AssertionError" message="Email was not sent successfully! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Email was not sent successfully! expected [true] but found [false]
at attendanceTests.AccessControlTests.testAccessGrantedRecordsRetrieval(AccessControlTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testAccessGrantedRecordsRetrieval -->
  <testcase classname="attendanceTests.LoginTests" name="verifyAccessControlMenuVisibleAfterLogin" time="0.047"/>
  <testcase classname="baseTestFile.BaseTests" name="@BeforeSuite globalSetUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetUp -->
  <testcase classname="baseTestFile.BaseTests" name="@AfterSuite globalTearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite globalTearDown -->
  <testcase classname="baseTestFile.BaseTests" name="@AfterSuite globalTearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite globalTearDown -->
  <testcase classname="baseTestFile.BaseTests" name="@BeforeSuite globalSetUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite globalSetUp -->
</testsuite> <!-- Surefire test -->
